# https://github.com/stats-organization/github-readme-stats-action#readme
name: Update github-readme-stats cards

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate stats card
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=transparent&cache_seconds=21600&hide_border=true&hide_rank=true&custom_title=Stats&text_bold=false&show=reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage
          path: github-readme-stats-action/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generate pin cards
      - name: Generate pin card (pre-commit-terraform)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=antonbabenko&repo=pre-commit-terraform&theme=transparent&show_owner=true
          path: github-readme-stats-action/pin_pre-commit-terraform.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card (terraform-switcher)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=warrensbox&repo=terraform-switcher&theme=transparent&show_owner=true
          path: github-readme-stats-action/pin_terraform-switcher.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generate gist cards
      - name: Generate gist card (My list of Terraform-related CLI tools)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: gist
          options: id=24b922460aa09759d74a27b7740ecd0f&show_owner=false
          path: github-readme-stats-action/gist_24b922460aa09759d74a27b7740ecd0f.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gist card (My list of CLI tools for AWS SSM Session Manager)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: gist
          options: id=234e18b40145ac437a88476e93b3f12c&show_owner=false
          path: github-readme-stats-action/gist_234e18b40145ac437a88476e93b3f12c.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gist card (Sort Terraform (HCL) file by Resource Block Names using GNU `awk`)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: gist
          options: id=7e0cf991962680d406692e1db1b551e6&show_owner=false
          path: github-readme-stats-action/gist_7e0cf991962680d406692e1db1b551e6.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gist card (Jenkins `buildNotifier.groovy`)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: gist
          options: id=44e591251bea0a08d5124b80ac796ee7&show_owner=false
          path: github-readme-stats-action/gist_44e591251bea0a08d5124b80ac796ee7.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gist card (AWS Region Code from Name)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: gist
          options: id=4670e5103e42746cdd5dd0236c32c587&show_owner=false
          path: github-readme-stats-action/gist_4670e5103e42746cdd5dd0236c32c587.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate gist card (Python debug output for `requests`/`urllib3`)
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: gist
          options: id=55c46ee560f6693af380254e2d0198c1&show_owner=false
          path: github-readme-stats-action/gist_55c46ee560f6693af380254e2d0198c1.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Commit and push changes
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-readme-stats-action/*.svg
          git commit -m "Update github-readme-stats-action cards" || exit 0
          git push
